/**
 * 機密情報パターン辞書
 *
 * このファイルはファイル名ベースの機密情報検出に使用するパターン定義です。
 * 定期的なメンテナンスと拡充を推奨します。
 *
 * 準拠規制・基準:
 * - 個人情報保護法（日本）
 * - マイナンバー法（番号法）
 * - ISMS（ISO 27001）
 * - プライバシーマーク（JIS Q 15001）
 * - GDPR（EU一般データ保護規則）
 * - PCI DSS（クレジットカード業界セキュリティ基準）
 * - HIPAA（米国医療情報保護法）- 参考
 * - SOX法（内部統制）- 参考
 *
 * リスクレベル定義:
 * - critical: 漏洩時に法的責任・重大な損害が発生（罰則対象、訴訟リスク）
 * - high: 漏洩時に重大な業務影響・信用失墜（取引停止、報道リスク）
 * - medium: 漏洩時に業務影響あり（内部対応必要）
 * - low: 漏洩時の影響は限定的（注意喚起レベル）
 *
 * @version 1.0.0
 * @lastUpdated 2024-11-30
 */

export type SensitivityLevel = 'critical' | 'high' | 'medium' | 'low';

export interface PatternCategory {
  level: SensitivityLevel;
  description: string;
  legalBasis?: string; // 根拠法令
  patterns: RegExp[];
}

export const SENSITIVE_PATTERNS: Record<string, PatternCategory> = {
  // ================================================================================
  // 【Critical】法的保護対象 - 漏洩時に法的責任が発生
  // ================================================================================

  /**
   * 特定個人情報（マイナンバー関連）
   * 根拠: マイナンバー法（番号法）
   * 罰則: 4年以下の懲役または200万円以下の罰金
   */
  myNumber: {
    level: 'critical',
    description: '特定個人情報（マイナンバー）',
    legalBasis: 'マイナンバー法',
    patterns: [
      // 直接的な表現
      /マイナンバー/i,
      /マイナンバ/i, // 長音省略
      /個人番号/i,
      /my\s*number/i,
      /mynumber/i,
      // 関連用語
      /特定個人情報/i,
      /番号法/i,
      /社会保障.*番号/i,
      /税番号/i,
      /通知カード/i,
      /個人番号カード/i,
      /番号.*通知/i,
      /法定調書.*番号/i,
      /扶養控除.*番号/i,
      /源泉.*個人番号/i,
    ],
  },

  /**
   * 要配慮個人情報（センシティブ情報）
   * 根拠: 個人情報保護法第2条第3項
   * 本人同意なしの取得禁止、オプトアウト不可
   */
  sensitivePersonalInfo: {
    level: 'critical',
    description: '要配慮個人情報',
    legalBasis: '個人情報保護法',
    patterns: [
      // === 人種・民族 ===
      /人種/i,
      /民族/i,
      /出身地.*情報/i,
      /国籍.*一覧/i,
      /外国人.*登録/i,
      /在留.*カード/i,
      /永住.*許可/i,

      // === 信条・思想・宗教 ===
      /信条/i,
      /思想/i,
      /宗教/i,
      /信仰/i,
      /政治.*信条/i,
      /政党.*所属/i,
      /組合.*加入/i,
      /労働組合.*名簿/i,

      // === 社会的身分 ===
      /社会的身分/i,
      /門地/i,
      /出自/i,
      /被差別/i,
      /同和/i,

      // === 病歴・医療情報 ===
      /病歴/i,
      /既往歴/i,
      /既往症/i,
      /診断書/i,
      /診療録/i,
      /診療.*記録/i,
      /カルテ/i,
      /医療.*記録/i,
      /電子カルテ/i,
      /レセプト/i,
      /医療費.*明細/i,
      /処方箋/i,
      /処方.*履歴/i,
      /投薬.*記録/i,
      /手術.*記録/i,
      /入院.*記録/i,
      /通院.*記録/i,
      /検査.*結果/i,
      /血液.*検査/i,
      /尿.*検査/i,
      /レントゲン/i,
      /CT.*結果/i,
      /MRI.*結果/i,
      /medical.*record/i,
      /health.*record/i,
      /patient.*data/i,
      /patient.*info/i,
      /clinical.*data/i,

      // === 健康診断・健康情報 ===
      /健康診断/i,
      /健診.*結果/i,
      /人間ドック/i,
      /定期.*健診/i,
      /特定.*健診/i,
      /メタボ.*健診/i,
      /健康.*情報/i,
      /BMI.*一覧/i,
      /血圧.*記録/i,
      /体重.*記録/i,
      /バイタル/i,
      /vital.*sign/i,

      // === 障害情報 ===
      /障害者手帳/i,
      /障害.*等級/i,
      /障害.*認定/i,
      /障がい.*情報/i,
      /障害.*一覧/i,
      /身体.*障害/i,
      /知的.*障害/i,
      /精神.*障害/i,
      /発達.*障害/i,
      /療育.*手帳/i,
      /disability/i,

      // === 精神・メンタルヘルス ===
      /精神疾患/i,
      /精神.*病歴/i,
      /メンタルヘルス/i,
      /メンタル.*不調/i,
      /うつ病/i,
      /うつ.*診断/i,
      /鬱/i,
      /適応.*障害/i,
      /パニック.*障害/i,
      /不安.*障害/i,
      /双極性/i,
      /統合失調/i,
      /PTSD/i,
      /ストレスチェック/i,
      /ストレス.*診断/i,
      /産業医.*面談/i,
      /産業医.*記録/i,
      /休職.*診断/i,
      /復職.*診断/i,
      /mental.*health/i,

      // === 犯罪歴・非行歴 ===
      /犯罪歴/i,
      /犯罪.*経歴/i,
      /前科/i,
      /前歴/i,
      /逮捕歴/i,
      /逮捕.*記録/i,
      /起訴.*記録/i,
      /有罪.*判決/i,
      /服役.*記録/i,
      /保護.*観察/i,
      /少年.*非行/i,
      /criminal.*record/i,
      /arrest.*record/i,
      /conviction/i,

      // === 犯罪被害情報 ===
      /犯罪被害/i,
      /被害者.*情報/i,
      /被害者.*名簿/i,
      /DV.*被害/i,
      /ストーカー.*被害/i,
      /性.*被害/i,
      /虐待.*被害/i,
      /victim/i,

      // === 遺伝情報・ゲノム ===
      /遺伝子/i,
      /遺伝.*情報/i,
      /ゲノム/i,
      /DNA.*情報/i,
      /DNA.*検査/i,
      /遺伝子.*検査/i,
      /genetic.*data/i,
      /genetic.*test/i,
      /genome/i,
    ],
  },

  /**
   * 認証・アクセス情報
   * 漏洩時にシステム侵害、なりすまし被害リスク
   */
  credentials: {
    level: 'critical',
    description: '認証・アクセス情報',
    legalBasis: '不正アクセス禁止法',
    patterns: [
      // === パスワード・暗証番号 ===
      /パスワード/i,
      /password/i,
      /passwd/i,
      /パスワード.*一覧/i,
      /パスワード.*リスト/i,
      /pass.*一覧/i,
      /pass.*list/i,
      /pwd/i,
      /暗証番号/i,
      /暗証.*一覧/i,
      /PIN.*コード/i,
      /PIN.*一覧/i,
      /秘密.*質問/i,
      /合言葉/i,
      /ワンタイム.*パスワード/i,
      /OTP/i,
      /二段階.*認証/i,
      /2FA/i,
      /MFA/i,
      /認証.*コード/i,
      /recovery.*code/i,
      /backup.*code/i,

      // === ログイン・認証情報 ===
      /認証情報/i,
      /認証.*一覧/i,
      /credential/i,
      /auth.*info/i,
      /ログイン.*情報/i,
      /ログイン.*一覧/i,
      /login.*info/i,
      /login.*list/i,
      /アカウント.*情報/i,
      /アカウント.*一覧/i,
      /account.*info/i,
      /account.*list/i,
      /ユーザー.*ID.*一覧/i,
      /user.*id.*list/i,

      // === APIキー・トークン ===
      /API\s*key/i,
      /api_key/i,
      /apikey/i,
      /API.*キー/i,
      /API.*一覧/i,
      /アクセスキー/i,
      /access.*key/i,
      /access.*token/i,
      /シークレット/i,
      /シークレットキー/i,
      /secret.*key/i,
      /secret/i,
      /トークン/i,
      /token/i,
      /bearer/i,
      /oauth.*token/i,
      /refresh.*token/i,
      /JWT/i,
      /session.*token/i,
      /webhook.*secret/i,

      // === 暗号鍵・証明書 ===
      /秘密鍵/i,
      /秘密.*キー/i,
      /private.*key/i,
      /priv.*key/i,
      /公開鍵/i,
      /public.*key/i,
      /鍵.*ペア/i,
      /key.*pair/i,
      /証明書/i,
      /certificate/i,
      /\.pem/i,
      /\.key/i,
      /\.crt/i,
      /\.cer/i,
      /\.pfx/i,
      /\.p12/i,
      /SSL.*証明書/i,
      /TLS.*証明書/i,
      /SSH.*key/i,
      /SSH.*鍵/i,
      /RSA/i,
      /ECDSA/i,
      /ED25519/i,
      /暗号.*鍵/i,
      /encryption.*key/i,
      /signing.*key/i,
      /GPG.*key/i,
      /PGP.*key/i,

      // === クラウドサービス認証 ===
      /AWS.*credential/i,
      /AWS.*access/i,
      /AWS.*secret/i,
      /GCP.*credential/i,
      /GCP.*key/i,
      /Azure.*credential/i,
      /Azure.*key/i,
      /service.*account/i,
      /サービスアカウント/i,
      /IAM.*credential/i,
      /クラウド.*認証/i,
      /Heroku.*API/i,
      /Stripe.*key/i,
      /Twilio.*key/i,
      /SendGrid.*key/i,
      /Firebase.*key/i,
      /Slack.*token/i,
      /GitHub.*token/i,
      /GitLab.*token/i,

      // === データベース認証 ===
      /DB.*パスワード/i,
      /データベース.*認証/i,
      /database.*credential/i,
      /DB.*credential/i,
      /MySQL.*password/i,
      /PostgreSQL.*password/i,
      /MongoDB.*password/i,
      /Redis.*password/i,
      /connection.*string/i,
      /接続.*文字列/i,
    ],
  },

  /**
   * 金融・決済情報
   * 根拠: PCI DSS、割賦販売法
   */
  financialPayment: {
    level: 'critical',
    description: '金融・決済情報',
    legalBasis: 'PCI DSS, 割賦販売法',
    patterns: [
      // === クレジットカード ===
      /クレジットカード/i,
      /クレジット.*カード/i,
      /credit.*card/i,
      /creditcard/i,
      /カード番号/i,
      /カード.*番号/i,
      /card.*number/i,
      /PAN/i,
      /CVV/i,
      /CVC/i,
      /CVV2/i,
      /CVC2/i,
      /セキュリティコード/i,
      /security.*code/i,
      /有効期限.*カード/i,
      /expir.*date/i,
      /expiry/i,
      /カード.*名義/i,
      /cardholder/i,
      /デビットカード/i,
      /debit.*card/i,
      /プリペイドカード/i,
      /prepaid.*card/i,

      // === 銀行口座 ===
      /銀行口座/i,
      /銀行.*口座/i,
      /bank.*account/i,
      /口座番号/i,
      /口座.*番号/i,
      /account.*number/i,
      /普通.*口座/i,
      /当座.*口座/i,
      /定期.*口座/i,
      /貯蓄.*口座/i,
      /振込先/i,
      /振込.*一覧/i,
      /振込.*口座/i,
      /送金先/i,
      /送金.*口座/i,
      /支店コード/i,
      /支店.*番号/i,
      /金融機関コード/i,
      /金融機関.*番号/i,
      /銀行コード/i,
      /店番/i,
      /SWIFT/i,
      /IBAN/i,
      /BIC/i,
      /routing.*number/i,
      /ABA.*number/i,

      // === 決済情報 ===
      /決済情報/i,
      /決済.*データ/i,
      /payment.*info/i,
      /payment.*data/i,
      /billing.*info/i,
      /請求.*情報/i,
      /課金.*情報/i,
      /自動引落/i,
      /口座振替/i,
      /引落.*口座/i,

      // === 電子マネー・仮想通貨 ===
      /電子マネー/i,
      /e-money/i,
      /ウォレット.*情報/i,
      /wallet.*info/i,
      /仮想通貨/i,
      /暗号資産/i,
      /cryptocurrency/i,
      /ビットコイン.*アドレス/i,
      /bitcoin.*address/i,
      /イーサリアム.*アドレス/i,
      /ethereum.*address/i,
      /秘密.*シード/i,
      /seed.*phrase/i,
      /mnemonic/i,
      /private.*wallet/i,

      // === 保険・年金 ===
      /保険.*証券番号/i,
      /保険.*契約.*番号/i,
      /年金.*番号/i,
      /基礎年金番号/i,
      /年金.*手帳/i,
    ],
  },

  // ================================================================================
  // 【High】業務上重要な機密情報 - 漏洩時に重大な業務影響
  // ================================================================================

  /**
   * 人事・労務機密情報
   */
  hrConfidential: {
    level: 'high',
    description: '人事・労務機密情報',
    patterns: [
      // === 給与・報酬 ===
      /給与/i,
      /給料/i,
      /salary/i,
      /報酬/i,
      /賃金/i,
      /wage/i,
      /賞与/i,
      /ボーナス/i,
      /bonus/i,
      /年収/i,
      /年俸/i,
      /月収/i,
      /月給/i,
      /時給/i,
      /日給/i,
      /基本給/i,
      /手当/i,
      /allowance/i,
      /残業代/i,
      /overtime/i,
      /インセンティブ/i,
      /incentive/i,
      /歩合/i,
      /コミッション/i,
      /commission/i,
      /源泉徴収/i,
      /年末調整/i,
      /確定申告/i,
      /退職金/i,
      /severance/i,
      /payroll/i,
      /payslip/i,
      /給与明細/i,
      /給与.*一覧/i,
      /給与.*台帳/i,
      /賃金.*台帳/i,
      /報酬.*一覧/i,

      // === 評価・査定 ===
      /人事評価/i,
      /人事.*考課/i,
      /査定/i,
      /考課/i,
      /評定/i,
      /performance.*review/i,
      /performance.*evaluation/i,
      /評価.*シート/i,
      /評価.*結果/i,
      /評価.*一覧/i,
      /考課.*表/i,
      /昇格/i,
      /昇給/i,
      /降格/i,
      /降給/i,
      /昇進/i,
      /promotion/i,
      /等級/i,
      /グレード/i,
      /grade/i,
      /ランク/i,
      /rank/i,
      /目標管理/i,
      /MBO/i,
      /OKR/i,
      /KPI.*個人/i,
      /360度.*評価/i,
      /コンピテンシー/i,
      /competency/i,

      // === 採用・選考 ===
      /履歴書/i,
      /職務経歴/i,
      /経歴書/i,
      /resume/i,
      /CV/i,
      /curriculum.*vitae/i,
      /職歴/i,
      /学歴/i,
      /応募者/i,
      /候補者/i,
      /candidate/i,
      /applicant/i,
      /エントリー.*シート/i,
      /ES/i,
      /面接.*評価/i,
      /面接.*記録/i,
      /面接.*シート/i,
      /選考.*結果/i,
      /選考.*評価/i,
      /採用.*結果/i,
      /内定/i,
      /内定者/i,
      /不採用/i,
      /採用.*通知/i,
      /オファー.*レター/i,
      /offer.*letter/i,
      /リファレンスチェック/i,
      /身元.*調査/i,
      /バックグラウンド.*チェック/i,
      /background.*check/i,
      /適性.*検査/i,
      /SPI/i,
      /性格.*診断/i,

      // === 懲戒・処分 ===
      /懲戒/i,
      /処分/i,
      /disciplinary/i,
      /戒告/i,
      /譴責/i,
      /減給.*処分/i,
      /出勤停止/i,
      /降格.*処分/i,
      /諭旨.*解雇/i,
      /懲戒.*解雇/i,
      /始末書/i,
      /顛末書/i,
      /反省文/i,
      /警告書/i,
      /注意.*指導/i,
      /改善.*指導/i,
      /解雇/i,
      /termination/i,
      /退職勧奨/i,
      /退職.*勧告/i,
      /リストラ/i,
      /整理解雇/i,
      /希望退職/i,
      /早期退職/i,
      /退職.*一覧/i,

      // === 労働問題 ===
      /労働組合/i,
      /労組/i,
      /union/i,
      /労使.*交渉/i,
      /団体交渉/i,
      /労働.*争議/i,
      /ストライキ/i,
      /strike/i,
      /ハラスメント/i,
      /harassment/i,
      /パワハラ/i,
      /セクハラ/i,
      /マタハラ/i,
      /パタハラ/i,
      /モラハラ/i,
      /アカハラ/i,
      /カスハラ/i,
      /いじめ/i,
      /嫌がらせ/i,
      /内部通報/i,
      /公益通報/i,
      /whistleblow/i,
      /ホットライン/i,
      /相談.*窓口/i,
      /通報.*記録/i,
      /調査.*報告/i,
      /労災/i,
      /労働.*災害/i,
      /過労/i,
      /長時間.*労働/i,

      // === 勤怠・労務管理 ===
      /勤怠/i,
      /出退勤/i,
      /タイムカード/i,
      /打刻/i,
      /attendance/i,
      /欠勤/i,
      /遅刻/i,
      /早退/i,
      /有給/i,
      /有給休暇/i,
      /年休/i,
      /休暇.*残日数/i,
      /残業.*時間/i,
      /時間外/i,
      /深夜.*勤務/i,
      /休日.*出勤/i,
      /36協定/i,
      /労働時間/i,
      /シフト/i,
      /勤務.*表/i,
    ],
  },

  /**
   * 経営・財務機密情報
   */
  businessFinancial: {
    level: 'high',
    description: '経営・財務機密情報',
    patterns: [
      // === 財務諸表・決算 ===
      /決算/i,
      /決算書/i,
      /財務諸表/i,
      /財務.*報告/i,
      /貸借対照表/i,
      /バランスシート/i,
      /balance.*sheet/i,
      /損益計算書/i,
      /P\/L/i,
      /P&L/i,
      /profit.*loss/i,
      /income.*statement/i,
      /キャッシュフロー/i,
      /CF.*計算書/i,
      /cash.*flow/i,
      /株主.*資本/i,
      /financial.*statement/i,
      /annual.*report/i,
      /四半期.*報告/i,
      /quarterly.*report/i,
      /月次.*決算/i,
      /月次.*報告/i,
      /試算表/i,
      /勘定.*科目/i,
      /仕訳/i,
      /journal.*entry/i,
      /総勘定.*元帳/i,
      /general.*ledger/i,

      // === 売上・利益 ===
      /売上/i,
      /売上高/i,
      /revenue/i,
      /sales/i,
      /利益/i,
      /profit/i,
      /営業利益/i,
      /operating.*profit/i,
      /経常利益/i,
      /純利益/i,
      /net.*income/i,
      /粗利/i,
      /gross.*profit/i,
      /margin/i,
      /損失/i,
      /loss/i,
      /赤字/i,
      /黒字/i,
      /収益/i,
      /earnings/i,
      /EBITDA/i,
      /ROE/i,
      /ROA/i,
      /ROI/i,

      // === 予算・計画 ===
      /予算/i,
      /budget/i,
      /予算.*編成/i,
      /予算.*案/i,
      /予実/i,
      /予実.*管理/i,
      /事業計画/i,
      /事業.*計画書/i,
      /business.*plan/i,
      /経営計画/i,
      /経営.*戦略/i,
      /中期.*計画/i,
      /中計/i,
      /長期.*計画/i,
      /年度.*計画/i,
      /収支.*計画/i,
      /資金.*計画/i,
      /投資.*計画/i,
      /設備.*投資/i,
      /CAPEX/i,
      /forecast/i,
      /見通し/i,
      /業績.*予想/i,

      // === M&A・資本政策 ===
      /M&A/i,
      /買収/i,
      /acquisition/i,
      /合併/i,
      /merger/i,
      /統合/i,
      /吸収/i,
      /子会社化/i,
      /出資/i,
      /増資/i,
      /減資/i,
      /資本.*参加/i,
      /資本.*提携/i,
      /業務.*提携/i,
      /アライアンス/i,
      /alliance/i,
      /デューデリジェンス/i,
      /due.*diligence/i,
      /DD/i,
      /企業.*価値/i,
      /valuation/i,
      /バリュエーション/i,
      /企業.*評価/i,
      /株式.*価値/i,
      /EV/i,
      /EBITDA.*倍率/i,
      /ディール/i,
      /deal/i,
      /LOI/i,
      /MOU/i,
      /基本合意/i,
      /最終契約/i,
      /クロージング/i,
      /closing/i,
      /PMI/i,
      /統合.*計画/i,

      // === 株主・IR・インサイダー ===
      /株主/i,
      /shareholder/i,
      /stockholder/i,
      /投資家/i,
      /investor/i,
      /IR.*資料/i,
      /IR.*情報/i,
      /投資家.*向け/i,
      /investor.*relation/i,
      /株主.*総会/i,
      /AGM/i,
      /議決権/i,
      /配当/i,
      /dividend/i,
      /自社株買い/i,
      /buyback/i,
      /インサイダー/i,
      /insider/i,
      /未公開.*情報/i,
      /重要.*事実/i,
      /material.*information/i,
      /適時開示/i,
      /timely.*disclosure/i,
      /有価証券.*報告/i,
      /securities.*report/i,
      /EDINET/i,
      /TDnet/i,

      // === 資金調達・借入 ===
      /資金調達/i,
      /fundraising/i,
      /借入/i,
      /融資/i,
      /loan/i,
      /ローン/i,
      /金利/i,
      /利率/i,
      /interest.*rate/i,
      /返済/i,
      /repayment/i,
      /担保/i,
      /collateral/i,
      /保証/i,
      /guarantee/i,
      /社債/i,
      /bond/i,
      /コミットメントライン/i,
      /シンジケート/i,
      /syndicate/i,
      /IPO/i,
      /上場/i,
      /listing/i,
      /VC/i,
      /venture.*capital/i,
      /PE/i,
      /private.*equity/i,
      /Series.*A/i,
      /Series.*B/i,
      /ラウンド/i,
      /round/i,
    ],
  },

  /**
   * 契約・法務機密情報
   */
  legalConfidential: {
    level: 'high',
    description: '契約・法務機密情報',
    patterns: [
      // === 契約書 ===
      /契約書/i,
      /contract/i,
      /agreement/i,
      /覚書/i,
      /memorandum/i,
      /MOU/i,
      /MOA/i,
      /基本契約/i,
      /master.*agreement/i,
      /MSA/i,
      /個別契約/i,
      /注文書/i,
      /発注書/i,
      /purchase.*order/i,
      /PO/i,
      /業務委託/i,
      /委託契約/i,
      /請負契約/i,
      /派遣契約/i,
      /準委任/i,
      /SES/i,
      /ライセンス契約/i,
      /license.*agreement/i,
      /使用許諾/i,
      /売買契約/i,
      /取引契約/i,
      /販売契約/i,
      /代理店契約/i,
      /フランチャイズ/i,
      /franchise/i,
      /リース契約/i,
      /lease/i,
      /賃貸借/i,
      /loan.*agreement/i,
      /金銭消費貸借/i,

      // === 秘密保持 ===
      /秘密保持/i,
      /機密保持/i,
      /守秘義務/i,
      /NDA/i,
      /non.*disclosure/i,
      /confidentiality/i,
      /秘密.*情報/i,
      /confidential.*information/i,
      /開示.*情報/i,

      // === 知的財産 ===
      /特許/i,
      /patent/i,
      /特許.*出願/i,
      /patent.*application/i,
      /特許.*登録/i,
      /商標/i,
      /trademark/i,
      /TM/i,
      /®/i,
      /商標.*登録/i,
      /著作権/i,
      /copyright/i,
      /©/i,
      /知的財産/i,
      /知財/i,
      /IP/i,
      /intellectual.*property/i,
      /実用新案/i,
      /意匠/i,
      /design.*patent/i,
      /発明/i,
      /invention/i,
      /発明届/i,
      /職務発明/i,
      /ライセンス.*許諾/i,
      /ロイヤリティ/i,
      /royalty/i,
      /技術.*移転/i,
      /技術.*供与/i,
      /ノウハウ/i,
      /know.*how/i,
      /営業.*秘密/i,
      /trade.*secret/i,

      // === 訴訟・紛争 ===
      /訴訟/i,
      /litigation/i,
      /裁判/i,
      /lawsuit/i,
      /訴状/i,
      /complaint/i,
      /答弁書/i,
      /準備書面/i,
      /証拠/i,
      /evidence/i,
      /判決/i,
      /judgment/i,
      /紛争/i,
      /dispute/i,
      /係争/i,
      /クレーム/i,
      /claim/i,
      /苦情/i,
      /示談/i,
      /和解/i,
      /settlement/i,
      /調停/i,
      /mediation/i,
      /仲裁/i,
      /arbitration/i,
      /弁護士/i,
      /attorney/i,
      /lawyer/i,
      /法務.*見解/i,
      /legal.*opinion/i,
      /リーガル.*レビュー/i,
      /legal.*review/i,

      // === コンプライアンス・規制対応 ===
      /コンプライアンス/i,
      /compliance/i,
      /法令.*遵守/i,
      /規制.*対応/i,
      /regulatory/i,
      /監査.*対応/i,
      /audit.*response/i,
      /内部.*監査/i,
      /internal.*audit/i,
      /外部.*監査/i,
      /external.*audit/i,
      /監査.*報告/i,
      /audit.*report/i,
      /是正.*措置/i,
      /改善.*計画/i,
      /不正/i,
      /fraud/i,
      /違反/i,
      /violation/i,
      /処分/i,
      /penalty/i,
      /制裁/i,
      /sanction/i,
    ],
  },

  /**
   * 顧客・取引先情報
   */
  customerVendorData: {
    level: 'high',
    description: '顧客・取引先情報',
    patterns: [
      // === 顧客情報 ===
      /顧客/i,
      /customer/i,
      /client/i,
      /お客様/i,
      /得意先/i,
      /顧客.*リスト/i,
      /顧客.*一覧/i,
      /顧客.*名簿/i,
      /顧客.*台帳/i,
      /customer.*list/i,
      /client.*list/i,
      /顧客.*情報/i,
      /顧客.*データ/i,
      /customer.*data/i,
      /client.*data/i,
      /顧客.*DB/i,
      /顧客.*マスター/i,
      /customer.*master/i,
      /CRM/i,
      /顧客管理/i,
      /会員/i,
      /member/i,
      /会員.*リスト/i,
      /会員.*一覧/i,
      /会員.*情報/i,
      /ユーザー.*一覧/i,
      /user.*list/i,
      /購入.*履歴/i,
      /purchase.*history/i,
      /取引.*履歴/i,
      /transaction.*history/i,

      // === 取引先情報 ===
      /取引先/i,
      /仕入先/i,
      /vendor/i,
      /supplier/i,
      /サプライヤー/i,
      /外注先/i,
      /協力会社/i,
      /パートナー/i,
      /partner/i,
      /取引先.*リスト/i,
      /取引先.*一覧/i,
      /取引先.*台帳/i,
      /vendor.*list/i,
      /supplier.*list/i,
      /仕入先.*マスター/i,
      /発注先/i,

      // === 商談・案件 ===
      /商談/i,
      /案件/i,
      /opportunity/i,
      /deal/i,
      /見込み客/i,
      /見込み/i,
      /リード/i,
      /lead/i,
      /prospect/i,
      /プロスペクト/i,
      /ターゲット/i,
      /target/i,
      /パイプライン/i,
      /pipeline/i,
      /ファネル/i,
      /funnel/i,
      /受注/i,
      /失注/i,
      /成約/i,
      /win.*rate/i,
      /成約率/i,
      /受注.*予測/i,
      /フォーキャスト/i,
      /forecast/i,

      // === 価格・条件 ===
      /価格表/i,
      /価格.*一覧/i,
      /price.*list/i,
      /料金表/i,
      /rate.*card/i,
      /単価/i,
      /unit.*price/i,
      /仕切り/i,
      /仕切価格/i,
      /卸価格/i,
      /wholesale/i,
      /原価/i,
      /cost/i,
      /原価.*一覧/i,
      /原価.*表/i,
      /マージン/i,
      /margin/i,
      /利益率/i,
      /markup/i,
      /見積/i,
      /見積書/i,
      /quotation/i,
      /quote/i,
      /estimate/i,
      /提案書/i,
      /proposal/i,
      /RFP/i,
      /RFQ/i,
      /RFI/i,
      /入札/i,
      /bid/i,
      /tender/i,
      /取引条件/i,
      /支払条件/i,
      /payment.*term/i,
      /掛け率/i,
      /与信/i,
      /credit.*limit/i,
      /与信.*枠/i,
    ],
  },

  /**
   * 製品・開発機密情報
   */
  productDevelopment: {
    level: 'high',
    description: '製品・開発機密情報',
    patterns: [
      // === 製品企画・ロードマップ ===
      /製品.*企画/i,
      /product.*plan/i,
      /新製品/i,
      /new.*product/i,
      /製品.*開発/i,
      /product.*development/i,
      /ロードマップ/i,
      /roadmap/i,
      /リリース.*計画/i,
      /release.*plan/i,
      /マイルストーン/i,
      /milestone/i,
      /開発.*計画/i,
      /development.*plan/i,
      /開発.*スケジュール/i,
      /プロジェクト.*計画/i,
      /project.*plan/i,
      /企画書/i,
      /planning.*doc/i,

      // === 技術・設計 ===
      /設計書/i,
      /設計.*仕様/i,
      /design.*spec/i,
      /仕様書/i,
      /specification/i,
      /要件.*定義/i,
      /requirement/i,
      /機能.*仕様/i,
      /functional.*spec/i,
      /アーキテクチャ/i,
      /architecture/i,
      /システム.*設計/i,
      /system.*design/i,
      /詳細.*設計/i,
      /detail.*design/i,
      /基本.*設計/i,
      /概要.*設計/i,
      /ER図/i,
      /クラス図/i,
      /シーケンス図/i,
      /フローチャート/i,
      /flowchart/i,
      /データモデル/i,
      /data.*model/i,
      /API.*設計/i,
      /API.*仕様/i,
      /インターフェース.*仕様/i,
      /interface.*spec/i,

      // === ソースコード・ビルド ===
      /ソースコード/i,
      /source.*code/i,
      /プログラム/i,
      /program/i,
      /ソース.*一覧/i,
      /モジュール.*一覧/i,
      /リポジトリ/i,
      /repository/i,
      /ビルド.*手順/i,
      /build.*instruction/i,
      /デプロイ.*手順/i,
      /deploy.*instruction/i,
      /リリース.*手順/i,
      /release.*instruction/i,
      /環境.*構築/i,
      /environment.*setup/i,

      // === 研究開発 ===
      /研究.*開発/i,
      /R&D/i,
      /research/i,
      /技術.*調査/i,
      /技術.*検証/i,
      /PoC/i,
      /proof.*of.*concept/i,
      /プロトタイプ/i,
      /prototype/i,
      /実験/i,
      /experiment/i,
      /試作/i,
      /特許.*申請/i,
      /技術.*論文/i,
    ],
  },

  // ================================================================================
  // 【Medium】社内機密情報 - 漏洩時に業務影響あり
  // ================================================================================

  /**
   * 機密表示・分類ラベル
   */
  confidentialLabels: {
    level: 'medium',
    description: '機密表示・分類ラベル',
    patterns: [
      // === 日本語機密表示 ===
      /社外秘/i,
      /部外秘/i,
      /関係者.*限/i,
      /機密/i,
      /秘密/i,
      /極秘/i,
      /厳秘/i,
      /取扱.*注意/i,
      /要.*注意/i,
      /非公開/i,
      /未公開/i,
      /公開.*禁止/i,
      /転載.*禁止/i,
      /複製.*禁止/i,
      /持出.*禁止/i,
      /社内.*限定/i,
      /内部.*限定/i,
      /限定.*公開/i,

      // === 英語機密表示 ===
      /confidential/i,
      /secret/i,
      /top.*secret/i,
      /classified/i,
      /restricted/i,
      /internal.*only/i,
      /internal.*use/i,
      /private/i,
      /proprietary/i,
      /sensitive/i,
      /not.*for.*distribution/i,
      /do.*not.*share/i,
      /do.*not.*copy/i,
      /do.*not.*forward/i,

      // === ドラフト・下書き ===
      /draft/i,
      /草案/i,
      /案/i,
      /仮/i,
      /暫定/i,
      /WIP/i,
      /work.*in.*progress/i,
      /未完成/i,
      /検討中/i,
      /レビュー.*中/i,
      /承認.*前/i,
    ],
  },

  /**
   * インフラ・セキュリティ情報
   */
  infrastructureSecurity: {
    level: 'medium',
    description: 'インフラ・セキュリティ情報',
    patterns: [
      // === ネットワーク構成 ===
      /ネットワーク.*構成/i,
      /network.*diagram/i,
      /ネットワーク.*図/i,
      /network.*topology/i,
      /トポロジー/i,
      /IP.*アドレス.*一覧/i,
      /IP.*list/i,
      /IPアドレス.*表/i,
      /サブネット/i,
      /subnet/i,
      /VLAN/i,
      /ファイアウォール.*設定/i,
      /firewall.*config/i,
      /ACL/i,
      /ルーティング/i,
      /routing/i,
      /VPN.*設定/i,
      /VPN.*config/i,

      // === サーバー・インフラ ===
      /サーバー.*一覧/i,
      /server.*list/i,
      /サーバー.*構成/i,
      /server.*config/i,
      /インフラ.*構成/i,
      /infrastructure/i,
      /システム.*構成/i,
      /system.*config/i,
      /ホスト.*一覧/i,
      /host.*list/i,
      /インスタンス.*一覧/i,
      /instance.*list/i,
      /データセンター/i,
      /datacenter/i,
      /ラック.*配置/i,
      /rack.*layout/i,

      // === セキュリティ ===
      /脆弱性/i,
      /vulnerability/i,
      /CVE/i,
      /セキュリティ.*診断/i,
      /security.*assessment/i,
      /ペネトレーション/i,
      /penetration/i,
      /ペンテスト/i,
      /pentest/i,
      /脆弱性.*スキャン/i,
      /vulnerability.*scan/i,
      /セキュリティ.*監査/i,
      /security.*audit/i,
      /リスク.*評価/i,
      /risk.*assessment/i,
      /セキュリティ.*ポリシー/i,
      /security.*policy/i,
      /アクセス.*権限/i,
      /access.*permission/i,
      /権限.*一覧/i,
      /permission.*list/i,

      // === ログ・監査 ===
      /監査.*ログ/i,
      /audit.*log/i,
      /アクセス.*ログ/i,
      /access.*log/i,
      /操作.*ログ/i,
      /operation.*log/i,
      /認証.*ログ/i,
      /auth.*log/i,
      /エラー.*ログ/i,
      /error.*log/i,
      /セキュリティ.*ログ/i,
      /security.*log/i,
      /イベント.*ログ/i,
      /event.*log/i,
      /トレース/i,
      /trace/i,
    ],
  },

  /**
   * 個人情報（一般）
   */
  personalDataGeneral: {
    level: 'medium',
    description: '個人情報（一般）',
    legalBasis: '個人情報保護法',
    patterns: [
      // === 名簿・一覧 ===
      /個人情報/i,
      /personal.*data/i,
      /personal.*info/i,
      /PII/i,
      /名簿/i,
      /住所録/i,
      /連絡先.*一覧/i,
      /contact.*list/i,
      /社員.*名簿/i,
      /従業員.*一覧/i,
      /従業員.*名簿/i,
      /スタッフ.*リスト/i,
      /employee.*list/i,
      /staff.*list/i,
      /member.*list/i,
      /メンバー.*一覧/i,
      /役員.*名簿/i,
      /組合員.*名簿/i,
      /OB.*名簿/i,
      /同窓.*名簿/i,

      // === 連絡先情報 ===
      /電話番号.*一覧/i,
      /phone.*list/i,
      /携帯.*番号.*一覧/i,
      /mobile.*list/i,
      /メール.*アドレス.*一覧/i,
      /email.*list/i,
      /メーリングリスト/i,
      /mailing.*list/i,
      /緊急連絡先/i,
      /emergency.*contact/i,
      /連絡網/i,

      // === 身分証明 ===
      /免許証/i,
      /運転免許/i,
      /driver.*license/i,
      /パスポート/i,
      /passport/i,
      /旅券/i,
      /保険証/i,
      /健康保険証/i,
      /insurance.*card/i,
      /ID.*カード/i,
      /ID.*card/i,
      /社員証/i,
      /employee.*ID/i,
      /在留カード/i,
      /residence.*card/i,
      /住民票/i,
      /戸籍/i,
      /印鑑証明/i,
      /住民基本台帳/i,

      // === 写真・画像 ===
      /顔写真/i,
      /証明写真/i,
      /ID.*photo/i,
      /社員.*写真/i,
      /プロフィール.*写真/i,
      /profile.*photo/i,
    ],
  },

  // ================================================================================
  // 【Low】一般的な社内情報 - 注意喚起レベル
  // ================================================================================

  /**
   * 社内文書・会議資料
   */
  internalDocuments: {
    level: 'low',
    description: '社内文書・会議資料',
    patterns: [
      // === 会議・議事録 ===
      /議事録/i,
      /議事.*要旨/i,
      /meeting.*minutes/i,
      /minutes/i,
      /会議.*資料/i,
      /会議.*録/i,
      /meeting.*material/i,
      /meeting.*note/i,
      /打合せ/i,
      /打ち合わせ/i,
      /MTG.*資料/i,
      /ミーティング/i,
      /定例.*会議/i,
      /週次.*報告/i,
      /月次.*報告/i,
      /報告書/i,
      /report/i,
      /レポート/i,
      /weekly.*report/i,
      /monthly.*report/i,

      // === 社内規程・ルール ===
      /社内規程/i,
      /社内規則/i,
      /就業規則/i,
      /employment.*rule/i,
      /服務規程/i,
      /経理規程/i,
      /購買規程/i,
      /情報.*セキュリティ.*規程/i,
      /マニュアル/i,
      /manual/i,
      /手順書/i,
      /procedure/i,
      /作業.*手順/i,
      /SOP/i,
      /ガイドライン/i,
      /guideline/i,
      /ハンドブック/i,
      /handbook/i,
      /規約/i,
      /ポリシー/i,
      /policy/i,

      // === 組織・体制 ===
      /組織図/i,
      /org.*chart/i,
      /organization.*chart/i,
      /体制図/i,
      /座席表/i,
      /seating.*chart/i,
      /フロアマップ/i,
      /floor.*map/i,
      /内線.*番号/i,
      /内線.*一覧/i,
      /extension.*list/i,
      /部署.*一覧/i,
      /department.*list/i,
      /役職.*一覧/i,

      // === 予定・スケジュール ===
      /スケジュール/i,
      /schedule/i,
      /カレンダー/i,
      /calendar/i,
      /予定表/i,
      /行事.*予定/i,
      /年間.*予定/i,
      /annual.*schedule/i,
      /工程表/i,
      /ガントチャート/i,
      /gantt/i,
      /WBS/i,

      // === 研修・教育 ===
      /研修/i,
      /training/i,
      /教育/i,
      /education/i,
      /オンボーディング/i,
      /onboarding/i,
      /新人.*研修/i,
      /OJT/i,
      /eラーニング/i,
      /e-learning/i,
    ],
  },
};

/**
 * 機密ファイル名を検出し、カテゴリとリスクレベルを返す
 */
export function detectSensitiveContent(fileName: string): {
  isSensitive: boolean;
  categories: string[];
  maxLevel: SensitivityLevel | null;
  details: { category: string; level: SensitivityLevel; description: string }[];
} {
  const details: { category: string; level: SensitivityLevel; description: string }[] = [];
  const categories: string[] = [];
  let maxLevel: SensitivityLevel | null = null;
  const levelPriority: Record<SensitivityLevel, number> = {
    critical: 4,
    high: 3,
    medium: 2,
    low: 1,
  };

  for (const [category, config] of Object.entries(SENSITIVE_PATTERNS)) {
    for (const pattern of config.patterns) {
      if (pattern.test(fileName)) {
        if (!categories.includes(category)) {
          categories.push(category);
          details.push({
            category,
            level: config.level,
            description: config.description,
          });

          // 最大リスクレベルを更新
          if (!maxLevel || levelPriority[config.level] > levelPriority[maxLevel]) {
            maxLevel = config.level;
          }
        }
        break; // 同カテゴリ内で1つマッチしたら次のカテゴリへ
      }
    }
  }

  return {
    isSensitive: categories.length > 0,
    categories,
    maxLevel,
    details,
  };
}

/**
 * カテゴリの日本語ラベルを取得
 */
export function getSensitiveCategoryLabel(category: string): string {
  const config = SENSITIVE_PATTERNS[category];
  return config?.description || category;
}

/**
 * リスクレベルに応じたポイントを取得
 */
export function getSensitivityPoints(level: SensitivityLevel): number {
  const points: Record<SensitivityLevel, number> = {
    critical: 25,
    high: 15,
    medium: 10,
    low: 5,
  };
  return points[level];
}

/**
 * パターン統計情報を取得
 */
export function getPatternStats(): {
  totalCategories: number;
  totalPatterns: number;
  byLevel: Record<SensitivityLevel, number>;
} {
  const stats = {
    totalCategories: Object.keys(SENSITIVE_PATTERNS).length,
    totalPatterns: 0,
    byLevel: {
      critical: 0,
      high: 0,
      medium: 0,
      low: 0,
    } as Record<SensitivityLevel, number>,
  };

  for (const config of Object.values(SENSITIVE_PATTERNS)) {
    stats.totalPatterns += config.patterns.length;
    stats.byLevel[config.level]++;
  }

  return stats;
}
